name: Release
on:
  push:
      tags:
        - 'v*'

env:
  # Must match the name of your TOC file for WoW to load this addon at all
  ADDON_NAME: TheAscendedQuests
  # The list of what you want to ship in your ZIP file, minus the TOC which is required
  ADDON_BUNDLE_FILES: TheAscendedQuests.lua LICENSE.md README.md
  # The ID of your project on CurseForge
  CURSE_ID: 449923
  # These cannot be parsed from the TOC, they must be manually set.
  CURSE_GAME_VERSIONS: 9.0.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Create 'dist' folder
      run: mkdir ${{env.ADDON_NAME}}/

    - name: Put everything into a folder
      run: cp -r ${{ env.ADDON_BUNDLE_FILES }} ${{ env.ADDON_NAME }}.toc ${{env.ADDON_NAME}}/
  
    - name: Zip it good
      run: zip -9 -r ${{env.ADDON_NAME}}.zip  ${{env.ADDON_NAME}}/
      
    - name: Parse WoW Addon Verions
      id: get_versions
      uses: icbat/parse-wow-addon-version@v1.0.1
      with:
        tocfile: ${{ env.ADDON_NAME }}.toc

    - name: Create GH Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_versions.outputs.addon_version }}
        release_name: Release ${{ steps.get_versions.outputs.addon_version }}
        draft: false
        prerelease: false
        
    - name: Upload GH Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.ADDON_NAME }}.zip
        asset_name: ${{ env.ADDON_NAME }}.zip
        asset_content_type: application/zip

    - name: Upload to CurseForge
      uses: itsmeow/curseforge-upload@v2
      with:
        token: ${{ secrets.CURSEFORGE_API_KEY }}
        project_id: ${{ env.CURSE_ID }}
        game_endpoint: wow
        file_path: ${{ env.ADDON_NAME }}.zip
        changelog: See ISSUELINK for latest changes
        game_versions: ${{ env.CURSE_GAME_VERSIONS }}
        release_type: release